twitter_routes/config/routes.rb
Rails.application.routes.draw do
  resources :puppies

  resources :users do 
    resources :puppies
  end

end

twitter_routes/app/models/puppy.rb
class Puppy < ActiveRecord::Base
end

twitter_routes/app/models/user.rb
class User < ActiveRecord::Base
end

twitter_routes/app/controllers/puppies_controller.rb
class PuppiesController < ApplicationController
  before_action :set_puppy, only: [:show, :edit, :update, :destroy]

  # GET /puppies
  # GET /puppies.json
  def index
    @puppies = Puppy.all
    if params[:user_id]
    @user = User.find(params[:user_id])
  end

  # GET /puppies/1
  # GET /puppies/1.json
  def show
  end

  # GET /puppies/new
  def new
    @puppy = Puppy.new
  end

  # GET /puppies/1/edit
  def edit
  end

  # POST /puppies
  # POST /puppies.json
  def create
    @puppy = Puppy.new(puppy_params)

    respond_to do |format|
      if @puppy.save
        format.html { redirect_to @puppy, notice: 'Puppy was successfully created.' }
        format.json { render :show, status: :created, location: @puppy }
      else
        format.html { render :new }
        format.json { render json: @puppy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /puppies/1
  # PATCH/PUT /puppies/1.json
  def update
    respond_to do |format|
      if @puppy.update(puppy_params)
        format.html { redirect_to @puppy, notice: 'Puppy was successfully updated.' }
        format.json { render :show, status: :ok, location: @puppy }
      else
        format.html { render :edit }
        format.json { render json: @puppy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /puppies/1
  # DELETE /puppies/1.json
  def destroy
    @puppy.destroy
    respond_to do |format|
      format.html { redirect_to puppies_url, notice: 'Puppy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_puppy
      @puppy = Puppy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def puppy_params
      params.require(:puppy).permit(:name, :breed, :size, :num_legs, :age)
    end
end

twitter_routes/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # before_action runs set_user before any of the other methods (show, edit, update, destroy)
  # the alternative would be to write @user = User.find(params[:id]) in show, edit, update, or destroy

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    # the only things that get through on the form are these things
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

twitter_routes/app/helpers/puppies_helper.rb
module PuppiesHelper
end

twitter_routes/app/helpers/users_helper.rb
module UsersHelper
end

twitter_routes/app/views/puppies/_form.html.erb
<%= form_for(@puppy) do |f| %>
  <% if @puppy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@puppy.errors.count, "error") %> prohibited this puppy from being saved:</h2>

      <ul>
      <% @puppy.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_area :name %>
  </div>
  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_area :breed %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_area :size %>
  </div>
  <div class="field">
    <%= f.label :num_legs %><br>
    <%= f.number_field :num_legs %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

twitter_routes/app/views/puppies/edit.html.erb
<h1>Editing puppy</h1>

<%= render 'form' %>

<%= link_to 'Show', @puppy %> |
<%= link_to 'Back', puppies_path %>

twitter_routes/app/views/puppies/index.html.erb
<h1>Listing puppies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Breed</th>
      <th>Size</th>
      <th>Num legs</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @puppies.each do |puppy| %>
      <tr>
        <td><%= puppy.name %></td>
        <td><%= puppy.breed %></td>
        <td><%= puppy.size %></td>
        <td><%= puppy.num_legs %></td>
        <td><%= puppy.age %></td>
        <td><%= link_to 'Show', puppy %></td>
        <td><%= link_to 'Edit', edit_puppy_path(puppy) %></td>
        <td><%= link_to 'Destroy', puppy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Puppy', new_puppy_path %>

twitter_routes/app/views/puppies/new.html.erb
<h1>New puppy</h1>

<%= render 'form' %>

<%= link_to 'Back', puppies_path %>

twitter_routes/app/views/puppies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @puppy.name %>
</p>

<p>
  <strong>Breed:</strong>
  <%= @puppy.breed %>
</p>

<p>
  <strong>Size:</strong>
  <%= @puppy.size %>
</p>

<p>
  <strong>Num legs:</strong>
  <%= @puppy.num_legs %>
</p>

<p>
  <strong>Age:</strong>
  <%= @puppy.age %>
</p>

<%= link_to 'Edit', edit_puppy_path(@puppy) %> |
<%= link_to 'Back', puppies_path %>

twitter_routes/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_area :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_area :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

twitter_routes/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

twitter_routes/app/views/users/index.html.erb
<h1>Listing users</h1>
<% if @user %>
<h1><%= @user.username %>'s puppies </h1>
<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <!-- "method:" is the same thing as ":method =>" --> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

twitter_routes/app/views/users/new.html.erb
<h1>New store</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

twitter_routes/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>