twitter_app/config/routes.rb
Rails.application.routes.draw do

  root "static_pages#home"

  get "/about_us" => "static_pages#about_us"
  get "/stuff" => "static_pages#stuff"
  get "/users" => "users#index"
  

end

twitter_app/app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user

end

twitter_app/app/models/twitter.rb
class Tweet < ActiveRecord::Base
	belongs_to :user
	#validates :user => true
	validates_presence_of :user_id, :message => "must be provided"

end

twitter_app/app/models/user.rb
class User < ActiveRecord::Base
	has_many :tweets
	validates :username, presence: true

	def tweet
		Tweet.new("some_stuff", self.id)
	end


end

# Tweet class needs a has_many

twitter_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def home
	end

	def about_us
	end

	def stuff
	end
	

end

twitter_app/app/controllers/users_controller.rb
class UsersController < ApplicationController

	def index
		@users = User.all
	end

end

twitter_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div>
	<!-- method call to "name", "link" -->
	<!-- you can also shorthand links with root_path for home and about_path for about us -->
	<%= link_to "Home", "/" %>
	<%= link_to "About", "/about_us" %>
	<%= link_to "Stuff", stuff_path %>


</div>



<%= yield %>

</body>
</html>

twitter_app/app/views/users/index.html.erb
<h1> Show us all the users </h1>

users should be here...
<% @users.each do |user| %>
<div><%= user.username %></div>
<div><%= user.password %></div>
<% end %>

<!-- rails.console
Users.create({username: "Lanya", password: "poop"})
User.new()
User.save
is a thing too
< % = displays information to the screen so you don't need them for for loops -->

<!-- 
	don't forget rails g migration createUserTable --> 